### ISSUE TITLE
Problems with latest om version?

### ISSUE THREAD

**Issue by jonase** [plumatic/om-tools#61]
I haven't been able to track this down but the following short snippet fails

```
(ns om-tools-issue.core
  (:require [om.core :as om]
            [om-tools.dom :as dom :include-macros true]
            [om-tools.core :refer-macros (defcomponent)]))

(defcomponent foo [_ _]
  (render [_]
    (dom/div (dom/div "ok?"))))

(om/root foo
         {}
         {:target (. js/document (getElementById "app"))})
```

If I change the outer div to `(dom/div nil ...)` the code works as expected. I'm using the following deps:

```
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2505"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [om "0.8.0-beta4"]
                 [prismatic/om-tools "0.3.6"]]
```

**Comment by jonase** [comment]
@loganlinn With the latest om-tools release (0.3.10) I'm still seeing similar issues. With **advanced compilation** I get

> Uncaught TypeError: Cannot read property 'call' of undefined

with `(dom/div (dom/div "ok?"))` but not with `(dom/div nil (dom/div "ok?"))`.

**Comment by jonase** [comment]
After some more investigation I suspect the reason is that [isValidElement](https://github.com/Prismatic/om-tools/blob/master/src/om_tools/dom.cljx#L108) is missing from the [externs](https://github.com/swannodette/react-cljs/blob/master/src/react/externs/react.js) file.

**Comment by hellofunk** [comment]
I have some additional information regarding the error mentioned above:

Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.

I am also getting this, tried with 0.3.9 through 0.3.11. I've spent quite a bit of time trying to track this one down and while the app seems to work just fine, my console is constantly active with hundreds of these. 

What I discovered is that this error appears when :optimizations are set to :none (which is a fully supported form of :optimization according to @dnolen). When I set it to :whitespace the error disappears.

This might help you pinpoint what is causing the issue in Om-tools, because this issue does not happen when using Om in isolation.
